<a href="https://colab.research.google.com/github/yunixi/python-ML/blob/main/sklearn_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn
print(sklearn.__version__)

0.22.2.post1


모델 구현을 위한 라이브러리 import

In [ ]:
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import pandas as pd
import numpy as np

#DecisionTreeClassifier : 의사 결정 트리 모델
#model_selection : 테스트, train 모델 구분

load_iris에서 제공하는 datasets은 많은게 있음
(리스트 보는 방법도 있음)

참고 : https://teddylee777.github.io/scikit-learn/scikit-learn-dataset

참고 : https://scikit-learn.org/stable/datasets

Iris 데이터셋 load 및 데이터 확인

In [ ]:
wine = load_wine()
wine_data = wine.data
wine_label = wine.target

print(wine_data)
print("=======================")
print(wine_label)
print("=======================")
print(wine.target_names)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
['class_0' 'class_1' 'class_2']


In [ ]:
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [ ]:
print(type(wine_data))

<class 'numpy.ndarray'>


In [ ]:
# pandas 데이터 프레임으로 가공
# pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
df_wine = pd.DataFrame(data = wine_data, columns=wine.feature_names)

# pandas 열 추가
df_wine['label'] = wine.target

df_wine.head(5)

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  label
0    14.23        1.71  2.43  ...                          3.92   1065.0      0
1    13.20        1.78  2.14  ...                          3.40   1050.0      0
2    13.16        2.36  2.67  ...                          3.17   1185.0      0
3    14.37        1.95  2.50  ...                          3.45   1480.0      0
4    13.24        2.59  2.87  ...                          2.93    735.0      0

[5 rows x 14 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(wine_data, wine_label, test_size=0.2, random_state = 30)
#Decision Model 생성
decisionModel = DecisionTreeClassifier(random_state = 30)
#fit으로 학습을 해줘야하기 때문에 정답지 SET x_train, y_train 값을 넣어줌
decisionModel.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=30, splitter='best')

In [ ]:
from sklearn.linear_model import LogisticRegression
logisticModel = LogisticRegression(random_state=5)
logisticModel.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=5, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
predDecision = decisionModel.predict(x_test)
predLogistic = logisticModel.predict(x_test)

In [ ]:
print('predict DecisionModel accurancy : {}'.format(accuracy_score(y_test, predDecision)) )
print('predict LogisticModel accurancy : {}'.format(accuracy_score(y_test, predLogistic)) )

predict DecisionModel accurancy : 0.8333333333333334
predict LogisticModel accurancy : 0.9722222222222222
